# Generated by Django 5.2.6 on 2025-09-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_applicant_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='parsed',
            field=models.JSONField(blank=True, null=True, verbose_name='Parsed Resume Data'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.TextField(verbose_name="Applicant's Resume Path"),
        ),
    ]
