# Generated by Django 5.2.6 on 2025-09-20 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_applicant_parsed_alter_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='embedding_stored',
            field=models.BooleanField(default=False, verbose_name='Embedding Stored Flag'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='AI Ranking Explanation'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name="Applicant's Resume File"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume_text',
            field=models.TextField(blank=True, verbose_name='Extracted Resume Text'),
        ),
        migrations.AlterField(
            model_name='college',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='api.applicant'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name="Applicant's Resume"),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='relevance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='relevance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
