# Generated by Django 5.2.6 on 2025-09-21 06:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_applicant_embedding_stored_applicant_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Relevance Explanation'),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Experience Relevance Explanation'),
        ),
        migrations.AddField(
            model_name='project',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Project Relevance Explanation'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.job', verbose_name='Job Applied For'),
        ),
        migrations.AlterField(
            model_name='college',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='college',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='relevance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Experience Relevance Score'),
        ),
        migrations.AlterField(
            model_name='project',
            name='relevance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Project Relevance Score'),
        ),
    ]
